import { taxValues,returnTotals,type TaxData,type ReturnRecord } from './Accounting';
import { useState } from 'react';
type Product={id:number;name:string;salePrice:number;cost:number};
type Order={returns?:ReturnRecord[];saleBasis?:string;id:number;customer:string;phone:string;date:string;status:string;courier:string;courierPay:number;courierSettled:boolean;deliveryFee:number;discount:number;paid:number;items:{productId:number;qty:number;name?:string;salePrice?:number;cost?:number}[]};
type Expense=TaxData & {id:number;date:string;title:string;category:string;amount:number};
type Purchase=TaxData & {id:number;date:string;material:string;quantity:number;unit:string;unitPrice:number;supplier:string;purchaseMode?:string;cartons?:number;unitsPerCarton?:number;cartonPrice?:number};
type Row=Record<string,string|number>;
type Kind='sales'|'purchases'|'expenses'|'delivery'|'all';
const names={sales:'المبيعات والأرباح',purchases:'المشتريات',expenses:'المصاريف',delivery:'التوصيل',all:'التقرير الشامل'};
const fields:Record<string,[string,string][]>= {
 sales:[['id','رقم الفاتورة'],['date','التاريخ'],['customer','العميل'],['phone','الهاتف'],['items','الأصناف والكميات'],['sale','قيمة الأصناف'],['discount','الخصم'],['deliveryFee','رسوم التوصيل'],['total','قيمة الطلب'],['cost','تكلفة الأصناف'],['courierPay','أجر الموصّل'],['profit','ربح الطلب'],['paid','المدفوع'],['remaining','المتبقي'],['status','الحالة'],['sentQty','الكمية المرسلة'],['returnQty','الكمية المرتجعة'],['soldQty','الكمية بعد المرتجع'],['returnCredit','قيمة المرتجعات'],['waste','تكلفة التالف'],['refundDue','واجب رده للعميل'],['saleBasis','طريقة البيع']],
 purchases:[['date','التاريخ'],['material','المادة'],['supplier','المورد'],['cartons','عدد الكراتين'],['unitsPerCarton','وحدات الكرتون'],['quantity','الكمية الإجمالية'],['unit','الوحدة'],['unitPrice','تكلفة الوحدة'],['taxMode','حالة الضريبة'],['taxRate','نسبة الضريبة %'],['base','قبل الضريبة'],['tax','الضريبة'],['total','الإجمالي']],
 expenses:[['date','التاريخ'],['title','الوصف'],['category','التصنيف'],['taxMode','حالة الضريبة'],['taxRate','نسبة الضريبة %'],['base','قبل الضريبة'],['tax','الضريبة'],['amount','الإجمالي']],
 delivery:[['id','رقم الفاتورة'],['date','التاريخ'],['customer','العميل'],['courier','الموصّل'],['courierPay','أجر التوصيل'],['status','حالة الطلب'],['settlement','تسوية المستحقات']]
};
const read=<T,>(key:string):T[]=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return []}};
const localDate=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const money=(n:number)=>n.toLocaleString('ar-OM',{minimumFractionDigits:3,maximumFractionDigits:3})+' ر.ع';
type Settings={kind:Kind;mode:string;month:string;from:string;to:string;customer:string;product:string;courier:string;status:string;payment:string;columns:Record<string,string[]>};
type Preset={name:string;settings:Settings};
export function ReportsPage({orders,products,expenses}:{orders:Order[];products:Product[];expenses:Expense[]}){
 const [settings,setSettings]=useState<Settings>(()=>({kind:'all',mode:'month',month:localDate().slice(0,7),from:localDate().slice(0,7)+'-01',to:localDate(),customer:'',product:'',courier:'',status:'',payment:'',columns:Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,v.map(f=>f[0])]))}));
 const [presets,setPresets]=useState(()=>read<Preset>('sweet-report-presets'));
 const [presetName,setPresetName]=useState('');const [error,setError]=useState('');
 const set=(key:keyof Settings,value:unknown)=>setSettings(s=>({...s,[key]:value}));
 const from=settings.mode==='month'?settings.month+'-01':settings.from;
 const to=settings.mode==='month'&&settings.month?(()=>{const [y,m]=settings.month.split('-').map(Number);return settings.month+'-'+new Date(y,m,0).getDate()})():settings.to;
 const valid=!!from&&!!to&&from<=to;
 const inRange=(date:string)=>valid&&date>=from&&date<=to;
 const sales:Row[]=orders.map(o=>{let sale=0,cost=0;const labels=o.items.map(i=>{const p=products.find(p=>p.id===i.productId);sale+=(i.salePrice??p?.salePrice??0)*i.qty;cost+=(i.cost??p?.cost??0)*i.qty;return (i.name??p?.name??'صنف محذوف')+' × '+i.qty});const returned=returnTotals(o.returns);const total=Math.max(sale-o.discount-returned.credit,0)+o.deliveryFee;return {...o,returns:'',courierSettled:o.courierSettled?'نعم':'لا',items:labels.join('، '),sale,cost,total,profit:total-cost-o.courierPay,remaining:Math.max(total-(o.paid-returned.refundPaid),0),sentQty:o.items.reduce((n,i)=>n+i.qty,0),returnQty:returned.qty,soldQty:o.items.reduce((n,i)=>n+i.qty,0)-returned.qty,returnCredit:returned.credit,waste:returned.waste,refundDue:Math.max(o.paid-returned.refundPaid-total,0),saleBasis:o.saleBasis==='consignment'?'بالأمانة (مبدئي حتى المرتجعات)':'بيع نهائي',settlement:o.courierSettled?'تمت التسوية':'غير مسوّى'} as Row}).filter(r=>inRange(String(r.date))&&(!settings.customer||r.customer===settings.customer)&&(!settings.courier||r.courier===settings.courier)&&(!settings.status?r.status!=='ملغي':r.status===settings.status)&&(!settings.payment||(settings.payment==='paid'?Number(r.remaining)===0:Number(r.remaining)>0))&&(!settings.product||orders.find(o=>o.id===r.id)?.items.some(i=>String(i.productId)===settings.product)));
 const purchases:Row[]=read<Purchase>('sweet-purchases').filter(r=>inRange(r.date)).map(r=>({...r,taxMode:r.taxMode??'غير محددة',base:taxValues(r.purchaseMode==='carton'?(r.cartons??0)*(r.cartonPrice??0):r.quantity*r.unitPrice,r).base,tax:taxValues(r.purchaseMode==='carton'?(r.cartons??0)*(r.cartonPrice??0):r.quantity*r.unitPrice,r).tax,cartons:r.purchaseMode==='carton'?r.cartons??0:'',unitsPerCarton:r.purchaseMode==='carton'?r.unitsPerCarton??0:'',total:taxValues(r.purchaseMode==='carton'?(r.cartons??0)*(r.cartonPrice??0):r.quantity*r.unitPrice,r).total}));
 const expenseRows:Row[]=expenses.filter(r=>inRange(r.date)).map(r=>({...r,taxMode:r.taxMode??'غير محددة',base:taxValues(r.amount,r).base,tax:taxValues(r.amount,r).tax,amount:taxValues(r.amount,r).total}));
 const delivery=sales.filter(r=>r.courier&&r.courier!=='بدون توصيل');
 const datasets:Record<string,Row[]>={sales,purchases,expenses:expenseRows,delivery};
 const kinds=settings.kind==='all'?Object.keys(fields):[settings.kind];
 const sum=(rows:Row[],key:string)=>rows.reduce((n,r)=>n+Number(r[key]||0),0);
 const activeSales=sales.filter(r=>r.status!=='ملغي');
 const summary:Row[]=[{label:'عدد الطلبات غير الملغاة',value:activeSales.length},{label:'قيمة المبيعات',value:sum(activeSales,'total')},{label:'المدفوع المسجل على الطلبات',value:sum(activeSales,'paid')},{label:'المتبقي',value:sum(activeSales,'remaining')},{label:'ربح الطلبات',value:sum(activeSales,'profit')},{label:'المصاريف',value:sum(expenseRows,'amount')},{label:'صافي تقديري بعد المصاريف',value:sum(activeSales,'profit')-sum(expenseRows,'amount')},{label:'المشتريات (لا تخصم مرة أخرى)',value:sum(purchases,'total')},{label:'ضريبة المشتريات',value:sum(purchases,'tax')},{label:'ضريبة المصاريف',value:sum(expenseRows,'tax')},{label:'قيمة المرتجعات',value:sum(activeSales,'returnCredit')},{label:'تكلفة التالف (ضمن تكلفة الإنتاج)',value:sum(activeSales,'waste')}];
 const filterText=[settings.customer&&'العميل: '+settings.customer,settings.courier&&'الموصّل: '+settings.courier,settings.status?'الحالة: '+settings.status:'استبعاد الملغاة',settings.payment&&'الدفع: '+(settings.payment==='paid'?'مكتمل':'متبقي'),settings.product&&'الصنف: '+products.find(p=>String(p.id)===settings.product)?.name].filter(Boolean).join(' | ');
 const columns=(k:string)=>fields[k].filter(([id])=>settings.columns[k]?.includes(id));
 const savePresets=(next:Preset[])=>{localStorage.setItem('sweet-report-presets',JSON.stringify(next));setPresets(next)};
 const select=(label:string,key:keyof Settings,options:string[])=> <label className="field"><span>{label}</span><select value={String(settings[key])} onChange={e=>set(key,e.target.value)}><option value="">الكل</option>{options.map(v=><option key={v}>{v}</option>)}</select></label>;
 return <section className="page reports-page"><div className="page-intro"><h1>التقارير</h1><p>ملخص شهري أو تقرير مخصص حسب الفترة والحقول المطلوبة.</p></div>
 <div className="panel report-controls"><div className="field-grid">
 <label className="field"><span>نوع التقرير</span><select value={settings.kind} onChange={e=>set('kind',e.target.value)}>{Object.entries(names).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label>
 <label className="field"><span>الفترة</span><select value={settings.mode} onChange={e=>set('mode',e.target.value)}><option value="month">شهر محدد</option><option value="range">مدة مخصصة</option></select></label>
 {settings.mode==='month'?<label className="field"><span>الشهر</span><input type="month" value={settings.month} onChange={e=>set('month',e.target.value)}/></label>:<><label className="field"><span>من</span><input type="date" value={settings.from} onChange={e=>set('from',e.target.value)}/></label><label className="field"><span>إلى</span><input type="date" value={settings.to} onChange={e=>set('to',e.target.value)}/></label></>}
 </div><p>يعتمد تاريخ الطلب على موعد الطلب المسجل، وتاريخ المشتريات والمصاريف على تاريخ كل سجل.</p>
 {(settings.kind==='sales'||settings.kind==='delivery'||settings.kind==='all')&&<div className="field-grid">{select('العميل','customer',Array.from(new Set(orders.map(o=>o.customer))))}{select('الموصّل','courier',Array.from(new Set(orders.map(o=>o.courier))))}{select('حالة الطلب','status',Array.from(new Set(orders.map(o=>o.status))))}<label className="field"><span>الصنف</span><select value={settings.product} onChange={e=>set('product',e.target.value)}><option value="">الكل</option>{products.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label className="field"><span>حالة الدفع</span><select value={settings.payment} onChange={e=>set('payment',e.target.value)}><option value="">الكل</option><option value="paid">مكتمل</option><option value="remaining">متبقي</option></select></label></div>}
 <p>فلاتر العميل والصنف والموصّل والحالة والدفع تخص الطلبات والتوصيل. فلتر الصنف يعرض كامل الطلبات التي تحتوي عليه.</p>
 {kinds.map(k=><fieldset key={k}><legend>{names[k as Kind]} — الأعمدة</legend><div className="report-columns">{fields[k].map(([id,label])=><label key={id}><input type="checkbox" checked={settings.columns[k]?.includes(id)} onChange={e=>set('columns',{...settings.columns,[k]:e.target.checked?[...(settings.columns[k]||[]),id]:settings.columns[k].filter(c=>c!==id)})}/>{label}</label>)}</div></fieldset>)}
 <div className="report-actions"><input placeholder="اسم إعداد التقرير" value={presetName} onChange={e=>setPresetName(e.target.value)}/><button className="primary" onClick={()=>{if(!presetName.trim()){setError('أدخل اسمًا للإعداد');return}savePresets([...presets.filter(p=>p.name!==presetName.trim()),{name:presetName.trim(),settings}]);setError('');}}>حفظ الإعداد</button><select defaultValue="" onChange={e=>{const p=presets.find(p=>p.name===e.target.value);if(p){setSettings(p.settings);setPresetName(p.name)}}}><option value="">تحميل إعداد محفوظ</option>{presets.map(p=><option key={p.name}>{p.name}</option>)}</select><button onClick={()=>{if(presetName&&confirm('حذف إعداد التقرير؟'))savePresets(presets.filter(p=>p.name!==presetName))}}>حذف الإعداد</button></div></div>
 {!valid&&<p role="alert" className="form-error">حدد فترة صحيحة؛ تاريخ البداية يجب أن يسبق النهاية أو يساويها.</p>}{error&&<p role="alert" className="form-error">{error}</p>}
 <div className="report-actions report-controls"><button className="primary" disabled={!valid||kinds.some(k=>!columns(k).length)} onClick={async()=>{try{setError('');const sheets:unknown[]=[['بيانات التقرير',['البيان','القيمة'],[['التقرير',names[settings.kind]],['من',from],['إلى',to],['الفلاتر',settings.kind==='sales'||settings.kind==='delivery'||settings.kind==='all'?filterText:'الفترة فقط'],['الأساس','موعد الطلب المسجل؛ المدفوع هو قيمة حالية وليس تحصيلًا بتاريخ الدفع']]]];if(settings.kind==='all'||settings.kind==='sales')sheets.push(['الملخص',['البيان','القيمة'],summary.map(r=>[r.label,r.value])]);if(settings.kind==='purchases')sheets.push(['الإجماليات',['البيان','القيمة'],[['إجمالي المشتريات',sum(purchases,'total')]]]);if(settings.kind==='expenses')sheets.push(['الإجماليات',['البيان','القيمة'],[['إجمالي المصاريف',sum(expenseRows,'amount')]]]);if(settings.kind==='delivery')sheets.push(['الإجماليات',['البيان','القيمة'],[['مستحقات الموصّلين',sum(delivery,'courierPay')],['غير مسوّى',sum(delivery.filter(r=>r.settlement==='غير مسوّى'),'courierPay')]]]);kinds.forEach(k=>sheets.push([names[k as Kind],columns(k).map(c=>c[1]),datasets[k].map(r=>columns(k).map(c=>r[c[0]]??''))]));await (window as unknown as {exportSweetsReport:(s:unknown[])=>Promise<void>}).exportSweetsReport(sheets)}catch{setError('تعذر التصدير. تأكد من تشغيل البرنامج المحلي.')}}}>تصدير Excel</button><button disabled={!valid||kinds.some(k=>!columns(k).length)} onClick={()=>window.print()}>طباعة / حفظ PDF</button><a href="/api/excel">تصدير جميع البيانات دون فلترة</a><span>لحفظ PDF اختر «حفظ بصيغة PDF» في نافذة الطباعة.</span></div>
 <div className="report-output">{valid&&sales.length===0&&(settings.kind==='sales'||settings.kind==='all'||settings.kind==='delivery')&&<p role="status">لا توجد طلبات مطابقة للفترة والفلاتر المحددة. غيّر الفترة أو استخدم «تصدير جميع البيانات دون فلترة» لتنزيل كل الطلبات المحفوظة.</p>}<h2>{names[settings.kind]}</h2><p>الفترة: {from} — {to}</p>{(settings.kind==='sales'||settings.kind==='delivery'||settings.kind==='all')&&<p>{filterText}</p>}
 {(settings.kind==='all'||settings.kind==='sales')&&<><div className="report-summary">{summary.map((r,i)=><div key={String(r.label)}><span>{r.label}</span><strong>{i===0?r.value:money(Number(r.value))}</strong></div>)}</div><p>المدفوع هو مجموع الدفعات المسجلة حاليًا على طلبات الفترة؛ لا يمثل تحصيلًا نقديًا خلال الفترة لأن تاريخ كل دفعة غير مسجل. قيم الطلبات تشمل المرتجعات المسجلة حتى الآن حتى لو كان تاريخ المرتجع خارج الفترة. طلبات الأمانة مبدئية حتى تسوية المرتجعات. صافي الربح تقديري، وتُعرض المشتريات منفصلة لتجنب خصم تكلفة الأصناف مرتين. فلاتر الطلبات لا تُطبّق على المصاريف.</p></>}
 {kinds.map(k=><div className="panel" key={k}><h3>{names[k as Kind]} ({datasets[k].length})</h3>{columns(k).length?<div className="report-table"><table><thead><tr>{columns(k).map(c=><th key={c[0]}>{c[1]}</th>)}</tr></thead><tbody>{datasets[k].map((r,i)=><tr key={i}>{columns(k).map(c=><td key={c[0]}>{typeof r[c[0]]==='number'&&!['id','quantity','cartons','unitsPerCarton','sentQty','returnQty','soldQty'].includes(c[0])?Number(r[c[0]]).toFixed(3):r[c[0]]}</td>)}</tr>)}</tbody></table>{!datasets[k].length&&<p>لا توجد سجلات مطابقة.</p>}</div>:<p>اختر عمودًا واحدًا على الأقل.</p>}{k==='purchases'&&<p>إجمالي المشتريات: {money(sum(purchases,'total'))}</p>}{k==='expenses'&&<p>إجمالي المصاريف: {money(sum(expenseRows,'amount'))}</p>}{k==='delivery'&&<p>مستحقات الموصّلين: {money(sum(delivery,'courierPay'))} | غير مسوّى: {money(sum(delivery.filter(r=>r.settlement==='غير مسوّى'),'courierPay'))}</p>}</div>)}
 </div></section>
}
